---
services:
  workflow.pacta.dashboard:
    build: .
    # stdin_open: true
    # tty: true
    # entrypoint: ["bash"]
    # entrypoint: ["R", "--args"]
    # command: '{\"portfolio\": {\"files\": [\"default_portfolio.csv\"], \"holdingsDate\": \"2023-12-31\", \"name\": \"FooPortfolio\"}, \"inherit\": \"GENERAL_2023Q4\"}'
    environment:
      LOG_LEVEL: TRACE
      ANALYSIS_OUTPUT_DIR: "/mnt/analysis_output_dir"
      BENCHMARKS_DIR: "/mnt/benchmarks_dir"
      DASHBOARD_DATA_DIR: "/mnt/dashboard_data"
    volumes:
      - type: bind
        source: ${benchmarks_dir:-./benchmarks_dir}
        target: /mnt/benchmarks_dir/
        read_only: true
      - type: bind
        source: ${analysis_output_dir:-./analysis_output_dir}
        target: /mnt/analysis_output_dir
        read_only: true
      - type: bind
        source: ${dashboard_data_dir:-./dashboard_data_dir}
        target: /mnt/dashboard_data
        read_only: false
