---
name: Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      full-image-name:
        required: true
        type: string

concurrency: preview-${{ github.ref }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: dashboard-build-*
          merge-multiple: false
          path: extracted_builds

      - name: Generate PR landing page
        working-directory: extracted_builds
        shell: bash
        run: |

          echo "<!DOCTYPE html><html><body>" > index.html
          for target_page in $(find */index.html)
          do
            echo "$target_page"
            link_text="$( \
              echo "$target_page" | \
              sed 's/^dashboard-build-//' | \
              sed 's/\/index\.html//' \
            )"
            echo "$link_text"
            echo "<a href=\"$target_page\">$link_text</a><br>" >> index.html
          done
          echo "</body></html>" >> index.html
          cat index.html

      - name: Show files
        run: |
          ls -laR extracted_builds

      - name: Add nojekyll file
        if: github.event.action != 'closed'
        run: touch dashboard_output_dir/.nojekyll

      - name: 🚀 Deploy main page
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dashboard_output_dir # The folder the action should deploy.
          clean: true
          force: false
          clean-exclude: |
            .nojekyll
            pr-preview/

      - name: 🛸 Deploy PR preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: extracted_builds
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
